env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/prefer-default-export: 0
  react/destructuring-assignment: 0
  react/prop-types: 0
  no-confusing-arrow: 0
  camelcase: 0
  max-len: 0
  react/jsx-props-no-spreading: 0
  react/jsx-one-expression-per-line: 0
  no-plusplus: 0