name: yarn
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn eslint "src/**"
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test --passWithNoTests
    - name: Check npm was NOT used
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "package-lock.json"
    - name: Check package-lock does not exist
      if: steps.check_files.outputs.files_exists == 'true'
      run: exit 1
